#:kivy 1.10.0

<WrapLabel@Label>:
    text_size: root.width, None
    size_hint_y: 0.2
    halign: 'center'
    valign: 'middle'
    font_size: 14
    

<DetGrid@GridLayout>:
    current_color: (0,0,0,0)

    canvas.before:
        Color:
            rgba: self.current_color
        Rectangle:
            size:self.size
            pos:self.pos

<MainButton@Button>:
	on_press:self.nav()

<NestedBox@BoxLayout>:
	orientation: 'vertical'
	spacing:10
